serve: true
port: 4000
lsi: false
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
markdown: kramdown
highlighter: rouge
incremental: true
permalink: /:year/:month/:day/:title
baseurl: ""

gems: ["jekyll-watch"]